version: '2'
services:
  app:
    container_name: wst-backoffice
    build: ./
    ports:
    - "8081:8081"
    depends_on:
    - postgresqldb
  postgresqldb:
    container_name: wst_postgres
    image: postgres
    volumes:
    - pg_volume:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: admin_wst
      POSTGRES_PASSWORD: wst!#4pas@*
      POSTGRES_DB: db_wst
volumes:
  pg_volume:
    name: wst_backoffice
