server:
  port: ${PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: @project.name@
  profiles:
    active: ${EXEC_ENVIRONMENT:local,credentials}
  datasource:
    url: ${POSTGRES_URL:${db.db_wst.url}}
    username: ${POSTGRES_USERNAME:${db.db_wst.username}}
    password: ${POSTGRES_PASSWORD:${db.db_wst.password}}
