server:
  port: ${PORT:${env.port:8081}}

spring:
  application:
    name: @project.name@
  profiles:
    active: ${EXEC_ENVIRONMENT:local}
  datasource:
    url: ${POSTGRES_URL:${db.db_wst.url}}
    username: ${POSTGRES_USERNAME:${db.db_wst.username}}
    password: ${POSTGRES_PASSWORD:${db_wst.password}}
