spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db_wst;MODE=PostgreSQL
      username: sa
      password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
