local.protocol: http://
server:
  port: 8081
  address: localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_wst
    username: admin_wst
    password: wst!#4pas@*
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
