server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/db_wst
    username: admin_wst
    password: wst!#4pas@*
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
