server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin_wst
    password: wst!#4pas@*
    url: jdbc:postgresql://localhost:5432/db_wst
    platform: postgres
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false