INSERT INTO country (alpha3code, name) VALUES ('AUS', 'Australia');
INSERT INTO country (alpha3code, name) VALUES ('ASS', 'Austria');
INSERT INTO country (alpha3code, name) VALUES ('AZE', 'Azerbaijan');
INSERT INTO country (alpha3code, name) VALUES ('BER', 'Bermuda');
INSERT INTO country (alpha3code, name) VALUES ('UKR', 'Ukraine');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('KNA', 'KN','Saint Kitts and Nevis');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('LCA', 'LC', 'Saint Lucia');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('VCT', 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('WSM', 'WS', 'Samoa');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('SMR', 'SM', 'San Marino');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('STP', 'ST', 'Sao Tome and Principe');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('SAU', 'SA', 'Saudi Arabia');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('PRK', 'KP', 'North Korea');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('HMD', 'HM', 'Heard Island and McDonald Islands');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('IMN', 'IM', 'Isle of Man');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('ISR', 'IL', 'Israel');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('MHL', 'MH', 'Marshall Islands');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('MNP', 'MP', 'Northern Mariana Islands');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('SGS', 'GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('USA', 'US', 'United States of America');
INSERT INTO country (alpha3code, alpha2code, name) VALUES ('COD', 'CD', 'Democratic Republic of the Congo');

